# Generated by Django 6.0.2 on 2026-03-03 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("algorithm", models.CharField(max_length=30, verbose_name="推荐算法")),
                ("score", models.FloatField(default=0, verbose_name="推荐得分")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="是否已完成"),
                ),
                ("date", models.DateField(verbose_name="推荐日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_recommendations",
                        to="questions.question",
                        verbose_name="推荐题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_recommendations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "每日推荐",
                "verbose_name_plural": "每日推荐",
                "db_table": "daily_recommendations",
                "ordering": ["-date", "-score"],
                "unique_together": {("user", "question", "date")},
            },
        ),
        migrations.CreateModel(
            name="QuestionSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity", models.FloatField(default=0, verbose_name="相似度")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "question_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities_as_a",
                        to="questions.question",
                        verbose_name="题目A",
                    ),
                ),
                (
                    "question_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities_as_b",
                        to="questions.question",
                        verbose_name="题目B",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目相似度",
                "verbose_name_plural": "题目相似度",
                "db_table": "question_similarities",
                "unique_together": {("question_a", "question_b")},
            },
        ),
        migrations.CreateModel(
            name="UserSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity", models.FloatField(default=0, verbose_name="相似度")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities_as_a",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户A",
                    ),
                ),
                (
                    "user_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities_as_b",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户B",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户相似度",
                "verbose_name_plural": "用户相似度",
                "db_table": "user_similarities",
                "unique_together": {("user_a", "user_b")},
            },
        ),
    ]
