# Generated by Django 6.0.2 on 2026-03-02 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "一级分类",
                "verbose_name_plural": "一级分类",
                "db_table": "categories",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[("text", "简答题"), ("code", "代码题")],
                        max_length=10,
                        verbose_name="题目类型",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="题目标题")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "简单"),
                            ("medium", "中等"),
                            ("hard", "困难"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="难度等级",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="questions.category",
                        verbose_name="一级分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目",
                "verbose_name_plural": "题目",
                "db_table": "questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CodeQuestionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="题目描述")),
                ("test_cases", models.JSONField(default=list, verbose_name="测试用例")),
                (
                    "reference_code",
                    models.TextField(blank=True, default="", verbose_name="参考代码"),
                ),
                (
                    "code_template",
                    models.JSONField(blank=True, default=dict, verbose_name="代码模板"),
                ),
                (
                    "time_limit",
                    models.IntegerField(default=1000, verbose_name="时间限制(ms)"),
                ),
                (
                    "memory_limit",
                    models.IntegerField(default=256, verbose_name="内存限制(MB)"),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_detail",
                        to="questions.question",
                        verbose_name="关联题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "代码题详情",
                "verbose_name_plural": "代码题详情",
                "db_table": "code_question_details",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="子分类名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_categories",
                        to="questions.category",
                        verbose_name="所属一级分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "二级分类",
                "verbose_name_plural": "二级分类",
                "db_table": "sub_categories",
                "ordering": ["sort_order", "id"],
                "unique_together": {("category", "name")},
            },
        ),
        migrations.AddField(
            model_name="question",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="questions.subcategory",
                verbose_name="二级分类",
            ),
        ),
        migrations.CreateModel(
            name="TextQuestionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="题干补充"),
                ),
                ("standard_answer", models.TextField(verbose_name="标准答案")),
                (
                    "explanation",
                    models.TextField(blank=True, default="", verbose_name="详细解析"),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_detail",
                        to="questions.question",
                        verbose_name="关联题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "简答题详情",
                "verbose_name_plural": "简答题详情",
                "db_table": "text_question_details",
            },
        ),
    ]
