# Generated by Django 6.0.2 on 2026-03-10 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_count",
                    models.IntegerField(default=0, verbose_name="提交次数"),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, verbose_name="通过次数"),
                ),
                (
                    "average_score",
                    models.FloatField(default=0.0, verbose_name="平均分"),
                ),
                ("pass_rate", models.FloatField(default=0.0, verbose_name="通过率")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat",
                        to="questions.question",
                        verbose_name="题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目统计数据",
                "verbose_name_plural": "题目统计数据",
                "db_table": "question_stats",
                "ordering": ["-updated_at"],
            },
        ),
    ]
