# Generated by Django 6.0.2 on 2026-03-03 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgeTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=20, verbose_name="编程语言")),
                ("source_code", models.TextField(verbose_name="源代码")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("accepted", "通过"),
                            ("wrong_answer", "答案错误"),
                            ("time_limit", "超时"),
                            ("memory_limit", "内存超限"),
                            ("runtime_error", "运行错误"),
                            ("compile_error", "编译错误"),
                            ("system_error", "系统错误"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "passed_count",
                    models.IntegerField(default=0, verbose_name="通过用例数"),
                ),
                (
                    "total_count",
                    models.IntegerField(default=0, verbose_name="总用例数"),
                ),
                (
                    "time_used",
                    models.FloatField(default=0, verbose_name="最大运行时间(ms)"),
                ),
                (
                    "memory_used",
                    models.FloatField(default=0, verbose_name="最大内存(KB)"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "detail",
                    models.JSONField(default=list, verbose_name="各用例详细结果"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge_tasks",
                        to="questions.question",
                        verbose_name="题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "判题任务",
                "verbose_name_plural": "判题任务",
                "db_table": "judge_tasks",
                "ordering": ["-created_at"],
            },
        ),
    ]
