# Generated by Django 6.0.2 on 2026-03-02 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.TextField(verbose_name="用户答案/代码")),
                ("score", models.FloatField(default=0, verbose_name="评分(0-100)")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="是否正确/通过"),
                ),
                (
                    "scoring_method",
                    models.CharField(
                        choices=[
                            ("model", "内嵌模型评分"),
                            ("deepseek", "DeepSeek API评分"),
                            ("judge", "代码判题"),
                        ],
                        max_length=20,
                        verbose_name="评分方式",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="编程语言"
                    ),
                ),
                (
                    "time_spent",
                    models.IntegerField(default=0, verbose_name="答题耗时(秒)"),
                ),
                (
                    "ai_feedback",
                    models.TextField(blank=True, default="", verbose_name="AI评语"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="questions.question",
                        verbose_name="题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "答题记录",
                "verbose_name_plural": "答题记录",
                "db_table": "submission_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserQuestionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_count",
                    models.IntegerField(default=0, verbose_name="提交次数"),
                ),
                ("best_score", models.FloatField(default=0, verbose_name="历史最高分")),
                (
                    "latest_score",
                    models.FloatField(default=0, verbose_name="最近一次得分"),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, verbose_name="是否已掌握(基于最近一次)"
                    ),
                ),
                (
                    "is_in_mistake_book",
                    models.BooleanField(default=False, verbose_name="是否在错题本中"),
                ),
                (
                    "first_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="首次作答时间"
                    ),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近作答时间"
                    ),
                ),
                (
                    "total_time_spent",
                    models.IntegerField(default=0, verbose_name="累计答题耗时(秒)"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_statuses",
                        to="questions.question",
                        verbose_name="题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_statuses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户题目状态",
                "verbose_name_plural": "用户题目状态",
                "db_table": "user_question_status",
                "unique_together": {("user", "question")},
            },
        ),
    ]
